### ISSUE TITLE
Array of game types is missing in ItemInfo.java

### ISSUE THREAD

**Issue by aureldussauge** [Nithanim/gw2api#1]
According to https://wiki.guildwars2.com/wiki/API:2/items, items are supposed to contain an array of game_types. I don't find this field in ItemInfo.java, is it normal ?

**Comment by Nithanim** [comment]
Indeed, I created the enum GameType but I forgot to include it into ItemInfo itself. No, this is not normal and there are most likely more little (or bigger) things that are messed up or were even added after the mapping was written. So please keep reporting them! :)

**Comment by Nithanim** [comment]
Commit https://github.com/Nithanim/gw2api/commit/26047a4ee7c4efa5056d58a4a3cb756c05ff0eaa should fix the issue.

**Comment by aureldussauge** [comment]
Ok thanks
