### ISSUE TITLE
Concentration & Condition Duration attribute types on items return null

### ISSUE THREAD

**Issue by feltax** [Nithanim/gw2api#16]
Hi there, really appreciate the wrapper,
There's an issue I've found where Concentration & Condition Duration attribute types on items are not parsed and return as null when retrieving them from an ItemInfo object. For example the Vigilant version of the pearl broadsword (https://wiki.guildwars2.com/wiki/Pearl_Broadsword) @ https://api.guildwars2.com/v2/items/70527
I assume this is due to these being new types of attributes included in the HoT expansion?
If this is an issue on my end, please let me know. I'm fairly basic at all this.
Kind regards,
Oliver

**Comment by Nithanim** [comment]
Thank you so much for your bug report! It helps me a lot when specific items are included that break everything.
There were indeed new AttributeTypes added to the official api. I added them now (hopefully all; the wiki is not complete) and will push them shortly. If everything goes right there should be a new build available in the snapshot repository in the next few minutes.

**Comment by Nithanim** [comment]
The version of this build is "0.0.4-20160426.101011-2" found in the snapshot repository at https://github.com/Nithanim/gw2api/issues/6#issuecomment-204593184.
Please let me know if you encounter any more problems using my gw2api!
