### ISSUE TITLE
Error when fetching all item infos

### ISSUE THREAD

**Issue by tgalaj** [Nithanim/gw2api#17]
When I try running the following code:

``` java
ItemsResource items =  GW2API.items();
int[] itemsIds = items.getOverview();
ItemInfo[] item_infos =  items.get(itemsIds); //error here
```

I get the following error: 

> Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:189)

**Comment by Nithanim** [comment]
The exception is a mistake on my part while generating (and in this case swallowing) a meaningful exception. I am sorry about that and I will fix that at some point. What you are really getting is a error 414 with 

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Request URL Too Long</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Request URL Too Long</h2>
<hr><p>HTTP Error 414. The request URL is too long.</p>
</BODY></HTML>
```

What you are doing is an extreme overkill is both not supported by me nor the official api. Only very few endpoints support an "all" when requesting ids but right now I can't even think of any endpoint that allows that.
In numbers, with this simple call, you are currently requesting the full details of 54704 items with a query string that has 318958 characters. [This string exceeds the 8000 recommended character minimum by specification only a _little_ bit which is not even supported by most browsers (more like around 2000).](http://stackoverflow.com/a/417184/2060704) :P

Jokes aside: I really hope you do not need all that and you can only request what you need. If you _really_ need everything then you have to break the request down in little chunks and fetch the information one by one. It might be a good idea to store that into a persistent database somehow.

**Comment by tgalaj** [comment]
Yes, you are right. After dividing these data into smaller chunks, everything works like a charm.

Thanks for the fast support :)
