### ISSUE TITLE
Id field in TokenInfo

### ISSUE THREAD

**Issue by aureldussauge** [Nithanim/gw2api#7]
Hello, 
The field id in TokenInfo.java must be a String, could you fix that please ?

**Comment by Nithanim** [comment]
It should be fixed with 7c67533c9fc2ae7cf225d382ad09e014bc26c4fd. I have deployed a snapshot into the snapshot repository. Let's find out if that works. You may need to tell gradle/maven to look for a new snapshot since i think the the (default) cache time is one day in both applications.

**Comment by aureldussauge** [comment]
It works !

**Comment by Nithanim** [comment]
That is great! I didn't expect that to be honest.
