### ISSUE TITLE
ItemInfo id is always 0

### ISSUE THREAD

**Issue by aureldussauge** [Nithanim/gw2api#8]
When I use for example 

``` java
ItemInfo item = new GuildWars2Api().items().get(id);
```

The field id (of BasicItem) is always 0.

**Comment by Nithanim** [comment]
Sorry, don't have time right now. Will look into it tomorrow-ish.

**Comment by aureldussauge** [comment]
No problem

**Comment by Nithanim** [comment]
That was a stupid mistake which should be fixed with 8e7ceb8 now but I may have introduced another issue with it ;)
